### ISSUE TITLE
Would you please release ERS_Python module?

### ISSUE THREAD

**Issue by hughplay** [wctu/SEAL#7]
I'm using Python3. 
I encountered ImportError when I imported ERSModule.
```
ImportError: /home/hongxin/opensource/SEAL/test/ERSModule.so: undefined symbol: Py_InitModule4_64
```
So, would you please release `ERS_Python`?

**Comment by wctu** [comment]
Thanks for your comment.
I put the code in the /test/ERS_Python folder.
If you find the code useful, please also give credit to the original ERS.
https://github.com/mingyuliutw/EntropyRateSuperpixel

**Comment by Ashish77IITM** [comment]
@hughplay @wctu  Even after having ERSPython file in test folder, I have encountered the same error on Linux while running test.py. How to solve this issue, please guide me. Thank You.

**Comment by wctu** [comment]
@Ashish77IITM The ERSModule.so module in the test folder is pre-built using Python 2. It is likely you are using Python 3 so that you have the ImportError issue. The solution is to use Python 2 to run the code or you need to re-build the module from ERSPython folder using Python 3 to obtain the correct module for your platform.
